# Generated by Django 5.2.13 on 2026-05-11 22:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Kullanıcı Mesajı')),
                ('response', models.TextField(blank=True, null=True, verbose_name='AI Cevabı')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'AI Sohbet Mesajı',
                'verbose_name_plural': 'AI Sohbet Mesajları',
                'ordering': ['-created_at'],
            },
        ),
    ]
