# Generated by Django 5.2.13 on 2026-05-11 21:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Araç', 'verbose_name_plural': 'Araçlar'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Depo', 'verbose_name_plural': 'Depolar'},
        ),
        migrations.AddField(
            model_name='product',
            name='critical_stock_level',
            field=models.IntegerField(default=10, verbose_name='Kritik Stok Seviyesi'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birim Fiyat'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(default=1000, verbose_name='Kapasite (kg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Sürücü'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='logistics.warehouse', verbose_name='Depo'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='capacity',
            field=models.IntegerField(verbose_name='Kapasite (m³)'),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_code', models.CharField(max_length=50, unique=True, verbose_name='Sevkiyat Kodu')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miktar')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('in_transit', 'Yolda'), ('delivered', 'Teslim Edildi'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('shipment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sevkiyat Tarihi')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sürücü')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.product', verbose_name='Ürün')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.vehicle', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Sevkiyat',
                'verbose_name_plural': 'Sevkiyatlar',
            },
        ),
    ]
