# Generated by Django 5.2.13 on 2026-05-01 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Plaka')),
                ('vehicle_type', models.CharField(max_length=50, verbose_name='Araç Tipi')),
                ('is_available', models.BooleanField(default=True, verbose_name='Müsait mi?')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Depo Adı')),
                ('location', models.CharField(max_length=255, verbose_name='Konum')),
                ('capacity', models.IntegerField(verbose_name='Kapasite (m3)')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Stok Kodu')),
                ('category', models.CharField(max_length=100, verbose_name='Kategori')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stok Miktarı')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='logistics.warehouse')),
            ],
        ),
    ]
